version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  nlp_service:
    build:
      context: ./microservices/nlp-service
    ports:
      - "5001:5001"
  notification_service:
    build:
      context: ./microservices/notification-service
    ports:
      - "5002:5002"
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"